### ISSUE TITLE
Implementation failure questions

### ISSUE THREAD

**Issue by binnythomas-1989** [iyacontrol/add-ebs-tags-controller#2]
By the way can you confirm if this is the way to implement

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
    volume.beta.kubernetes.io/aws-block-storage-additional-resource-tags: "map_migrated=map-migrated"
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

Kindly confirm

The approach is correct
Do we require to deploy this controller in each namespace
